---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: kubernetes
  namespace: agentgateway-system
spec:
  mcp:
    targets:
      - name: kubernetes
        static:
          host: host.minikube.internal
          port: 8443
          path: /mcp
          protocol: StreamableHTTP
