---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: graphiti-openai
  namespace: agentgateway-system
spec:
  ai:
    groups:
      - providers:
          - name: openai
            openai: {}
            policies:
              auth:
                secretRef:
                  name: vicegerent-openai-secrets
              ai:
                routes:
                  /v1/embeddings: Embeddings
                  /v1/chat/completions: Completions
                  '*': Passthrough
