---
# Upstream default values:
# https://github.com/cilium/tetragon/blob/v1.7.0/install/kubernetes/tetragon/values.yaml
crds:
  installMethod: helm
tetragon:
  exportAllowList: |-
    {"namespace":["agent-sandbox"],"event_set":["PROCESS_EXEC","PROCESS_KPROBE"]}
  extraArgs:
    rb-size-total: 8M
    rb-queue-size: '262144'
    event-queue-size: '40000'
