---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vicegerent-agent.name" . }}-sandbox-spec
  namespace: agent-sandbox
data:
  sandbox.yaml: |-
    {{- include "vicegerent-agent.sandbox" . | nindent 4 }}
