---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "vicegerent-agent.name" . }}-secrets
  namespace: agent-sandbox
spec:
  itemPath: vaults/Vicegerent/items/Agent - {{ include "vicegerent-agent.name" . }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "vicegerent-agent.name" . }}-agentgateway-api-key
  namespace: agent-sandbox
spec:
  itemPath: vaults/Vicegerent/items/Agent - {{ include "vicegerent-agent.name" . }} agentgateway API key
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "vicegerent-agent.name" . }}-ssh-key
  namespace: agent-sandbox
spec:
  itemPath: vaults/Vicegerent/items/Agent - {{ include "vicegerent-agent.name" . }} SSH Key
