---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentgateway-system
resources:
  - gateway.yaml
  - networkpolicy.yaml
  - egress-networkpolicy.yaml
  - apikey-policy.yaml
commonAnnotations:
  kustomize.toolkit.fluxcd.io/force: Enabled
