---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: kmcp
  namespace: agentgateway-system
spec:
  mcp:
    targets:
      - name: tavily
        static:
          host: tavily.kmcp.svc.cluster.local
          port: 3000
          path: /mcp
          protocol: StreamableHTTP
      - name: firecrawl
        static:
          host: firecrawl.kmcp.svc.cluster.local
          port: 3000
          path: /mcp
          protocol: StreamableHTTP
  policies:
    tcp:
      connectTimeout: 5s
    http:
      requestTimeout: 30s
