---
namespace:
  create: false
  name: agent-sandbox-system
image:
  repository: registry.k8s.io/agent-sandbox/agent-sandbox-controller
  tag: v0.4.6
controller:
  extensions: false
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 128Mi
