---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
    crds: CreateReplace
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
    force: true
  chart:
    spec:
      chart: reloader
      version: 2.2.14
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: reloader
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: reloader-values
