{{- if eq (include "vicegerent-webhook-listener.enabled" .) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-listener
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: webhook-listener
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: webhook-listener
  ports:
    - name: http
      port: 8081
      targetPort: http
{{- end }}
