---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agent-sandbox
resources: [release.yaml]
configMapGenerator:
  - name: felix-values
    files: [values.yaml=values.yaml]
configurations: [kustomizeconfig.yaml]
