---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: anton
  namespace: agent-sandbox
spec:
  interval: 30m
  chart:
    spec:
      chart: ./charts/vicegerent-agent
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
      reconcileStrategy: Revision
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: anton-values
