---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cerbos
  namespace: cerbos
spec:
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    force: true
  chart:
    spec:
      chart: cerbos
      version: 0.54.0
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: cerbos
        namespace: cerbos
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: cerbos-values
