---
# Upstream default values:
# https://github.com/cerbos/helm-charts/blob/main/charts/cerbos/values.yaml
resources:
  requests:
    cpu: 50m
    memory: 64Mi
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10000
  runAsGroup: 10000
  fsGroup: 10000
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]
volumes:
  - name: policies
    configMap:
      name: cerbos-policies
volumeMounts:
  - name: policies
    mountPath: /policies
    readOnly: true
cerbos:
  logLevel: INFO
  config:
    storage:
      driver: disk
      disk:
        directory: /policies
        watchForChanges: true
