---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "vicegerent-mcp.name" . }}
  namespace: {{ include "vicegerent-mcp.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vicegerent-mcp.name" . }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: agentgateway-system
            gateway.networking.k8s.io/gateway-name: agentgateway-proxy
      toPorts:
        - ports:
            - port: '{{ .Values.port }}'
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: UDP
          rules:
            dns:
              - matchPattern: '*'
    {{- if .Values.networkPolicy.toFQDNs }}
    - toFQDNs:
        {{- range .Values.networkPolicy.toFQDNs }}
        - matchName: {{ . }}
        {{- end }}
      toPorts:
        - ports:
            - port: '443'
              protocol: TCP
    {{- end }}
