{{- range .Values.secrets }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .name }}
  namespace: {{ include "vicegerent-mcp.namespace" $ }}
spec:
  itemPath: {{ .itemPath }}
{{- end }}
