---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vicegerent-agent.name" . }}-config-reconciler
  namespace: agent-sandbox
data:
  reconcile-config.py: |-
{{ .Files.Get "files/reconcile-config.py" | indent 4 }}
