---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: haiku-oai
  namespace: agentgateway-system
spec:
  ai:
    groups:
      - providers:
          - name: anthropic-haiku-oai
            anthropic:
              model: claude-haiku-4-5
            policies:
              auth:
                secretRef:
                  name: vicegerent-secrets
              ai:
                routes:
                  /v1/chat/completions: Completions
                  '*': Passthrough
