---
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: tavily
  namespace: kmcp
spec:
  deployment:
    image: docker.io/node:24-alpine3.21
    cmd: npx
    args: [-y, tavily-mcp@0.2.20]
    port: 3000
    env:
      HOME: /home/node
      NODE_OPTIONS: --max-heap-size=200 --max-semi-space-size=16
    secretRefs:
      - name: tavily-api-key
    serviceAccountName: tavily
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
  stdioTransport: {}
  transportType: stdio
  timeout: 60s
