---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firecrawl-mcp
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - server.yaml
  - networkpolicy.yaml
