# Generated by host/brew/generate.py; edit host/brew/templates/ghostunnel.rb.in instead.
class GhostunnelAT1112 < Formula
  desc "Simple SSL/TLS proxy with mutual authentication"
  homepage "https://ghostunnel.dev/"
  url "https://github.com/ghostunnel/ghostunnel/archive/refs/tags/v1.11.2.tar.gz"
  version "1.11.2"
  sha256 "77d369f25ec0f8439b198df7da4eae4aec901e16a8b39965a6fc14f15c80a002" # pragma: allowlist secret
  license "Apache-2.0"
  keg_only :versioned_formula

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(output: bin/"ghostunnel", ldflags: "-X main.version=#{version}")
    generate_completions_from_executable(bin/"ghostunnel", shell_parameter_format: "--completion-script-",
                                         shells: [:bash, :zsh])
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ghostunnel --version")
  end
end
