# Generated by host/brew/generate.py; edit host/brew/templates/supervisor.rb.in instead.
class SupervisorAT430 < Formula
  include Language::Python::Virtualenv

  desc "Process Control System"
  homepage "https://supervisord.org/"
  url "https://files.pythonhosted.org/packages/a9/b5/37e7a3706de436a8a2d75334711dad1afb4ddffab09f25e31d89e467542f/supervisor-4.3.0.tar.gz"
  version "4.3.0"
  sha256 "4a2bf149adf42997e1bb44b70c43b613275ec9852c3edacca86a9166b27e945e" # pragma: allowlist secret
  license "BSD-3-Clause-Modification"
  keg_only :versioned_formula

  depends_on "python@3.14"

  def install
    inreplace buildpath/"supervisor/skel/sample.conf" do |s|
      s.gsub! %r{/tmp/supervisor\.sock}, var/"run/supervisor.sock"
      s.gsub! %r{/tmp/supervisord\.log}, var/"log/supervisord.log"
      s.gsub! %r{/tmp/supervisord\.pid}, var/"run/supervisord.pid"
      s.gsub!(/^;\[include\]$/, "[include]")
      s.gsub! %r{^;files = relative/directory/\*\.ini$}, "files = #{etc}/supervisor.d/*.ini"
    end
    virtualenv_install_with_resources
    etc.install buildpath/"supervisor/skel/sample.conf" => "supervisord.conf"
    (var/"run").mkpath
    (var/"log").mkpath
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/supervisord --version")
  end
end
