# Generated by host/brew/generate.py; edit host/brew/templates/toolhive.rb.in instead.
class ThvAT0420 < Formula
  desc "ToolHive manager for MCP servers"
  homepage "https://github.com/stacklok/toolhive"
  version "0.42.0"
  license "Apache-2.0"
  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/toolhive/releases/download/v0.42.0/toolhive_0.42.0_darwin_amd64.tar.gz"
      sha256 "c8523c41157a7040b6ee3d9e6058056e388f553fac562892567f7971c6ce0729" # pragma: allowlist secret
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/toolhive/releases/download/v0.42.0/toolhive_0.42.0_darwin_arm64.tar.gz"
      sha256 "9aca8f82800c0d7b9ab8311859bd1152f8568a6abd5526917e1f97639bcdd598" # pragma: allowlist secret
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/toolhive/releases/download/v0.42.0/toolhive_0.42.0_linux_amd64.tar.gz"
      sha256 "3069ff8e41ca4e0b0bdfbb9dd37fd7da002e918e33701dcdb1afae7e27cf3370" # pragma: allowlist secret
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/toolhive/releases/download/v0.42.0/toolhive_0.42.0_linux_arm64.tar.gz"
      sha256 "09144b25b1c0aed5bff73453e1cb5364b4ff6ef5451f6a2b8e6d55843eabb1d3" # pragma: allowlist secret
    end
  end

  def install
    bin.install "thv"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/thv version")
  end
end
