---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: deepseek
  namespace: agentgateway-system
spec:
  ai:
    groups:
      - providers:
          - name: deepseek
            openai: {}
            host: api.deepseek.com
            port: 443
            policies:
              auth:
                secretRef:
                  name: vicegerent-deepseek-secrets
              tls:
                sni: api.deepseek.com
              ai:
                routes:
                  /v1/chat/completions: Completions
                  '*': Passthrough
