---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [backend.yaml, route.yaml]
components: [../_components/promptguard-secrets]
commonAnnotations:
  kustomize.toolkit.fluxcd.io/force: Enabled
