---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - reloader
  - metrics-server
  - agentgateway
  - agent-sandbox
  - cerbos
  - mcp-cerbos-shim
  - host-firewall
  - victoria-logs
