---
apiVersion: v1
kind: ConfigMap
metadata:
  name: langfuse-otel-collector-config
  namespace: langfuse
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    exporters:
      otlphttp/langfuse:
        endpoint: http://langfuse-web.langfuse.svc.cluster.local:3000/api/public/otel
        headers:
          Authorization: Basic ${env:LANGFUSE_OTEL_AUTH}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlphttp/langfuse]
