---
# https://github.com/langfuse/langfuse-k8s/blob/main/charts/langfuse/values.yaml
langfuse:
  features:
    telemetryEnabled: false
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
  nextauth:
    url: http://localhost:3000
    secret:
      secretKeyRef:
        name: langfuse-secrets
        key: nextauth-secret
  salt:
    secretKeyRef:
      name: langfuse-secrets
      key: salt
  encryptionKey:
    secretKeyRef:
      name: langfuse-secrets
      key: encryption-key
  ingress:
    enabled: false
postgresql:
  auth:
    existingSecret: langfuse-secrets  # pragma: allowlist secret
    secretKeys:
      userPasswordKey: postgres-password  # pragma: allowlist secret
      adminPasswordKey: postgres-password  # pragma: allowlist secret
  primary:
    resourcesPreset: none
    resources:
      requests:
        cpu: 25m
        memory: 128Mi
redis:
  auth:
    existingSecret: langfuse-secrets  # pragma: allowlist secret
    existingSecretPasswordKey: redis-password  # pragma: allowlist secret
  primary:
    resourcesPreset: none
    resources:
      requests:
        cpu: 15m
        memory: 64Mi
clickhouse:
  clusterEnabled: false
  replicaCount: 1
  resourcesPreset: none
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
  zookeeper:
    enabled: false
  auth:
    existingSecret: langfuse-secrets  # pragma: allowlist secret
    existingSecretKey: clickhouse-password  # pragma: allowlist secret
s3:
  auth:
    existingSecret: langfuse-secrets  # pragma: allowlist secret
    rootUserSecretKey: minio-root-user  # pragma: allowlist secret
    rootPasswordSecretKey: minio-root-password  # pragma: allowlist secret
  resourcesPreset: none
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
