---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cerbos
configMapGenerator:
  - name: cerbos-policies
    files: [defs/resource_k8s.yaml, defs/resource_grafana.yaml]
generatorOptions:
  disableNameSuffixHash: true
