---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cerbos
configMapGenerator:
  - name: cerbos-policies
    files:
      - defs/resource_k8s.yaml
      - defs/resource_grafana.yaml
      - defs/resource_jira.yaml
      - defs/resource_github.yaml
      - defs/resource_notion.yaml
      - defs/resource_gitlab.yaml
      - defs/resource_linear.yaml
      - defs/resource_alertmanager.yaml
      - defs/resource_pagerduty.yaml
generatorOptions:
  disableNameSuffixHash: true
