---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: zai
  namespace: agentgateway-system
spec:
  ai:
    groups:
      - providers:
          - name: zai
            openai: {}
            host: api.z.ai
            port: 443
            pathPrefix: /api/paas/v4
            policies:
              auth:
                secretRef:
                  name: vicegerent-zai-secrets
              tls:
                sni: api.z.ai
              ai:
                routes:
                  /api/paas/v4/chat/completions: Completions
                  '*': Passthrough
