---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: gitlab-mcp-tools
  namespace: agentgateway-system
spec:
  targetRefs:
    - group: agentgateway.dev
      kind: AgentgatewayBackend
      name: gitlab
  backend:
    mcp:
      authorization:
        action: Allow
        policy:
          matchExpressions:
            - >-
              mcp.tool.name in [
                "create_or_update_file",
                "search_repositories",
                "create_repository",
                "get_file_contents",
                "push_files",
                "create_issue",
                "create_merge_request",
                "fork_repository",
                "create_branch",
                "list_merge_requests",
                "get_merge_request",
                "get_merge_request_diffs",
                "list_merge_request_diffs",
                "update_merge_request",
                "list_issues",
                "get_issue",
                "update_issue",
                "list_projects",
                "get_project"
              ]
