---
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: gitlab
  namespace: kmcp
spec:
  deployment:
    image: docker.io/node:24-alpine3.21
    cmd: npx
    args: [-y, '@modelcontextprotocol/server-gitlab@2025.4.25']
    port: 3000
    env:
      HOME: /home/node
      NODE_OPTIONS: --max-old-space-size=200 --max-semi-space-size=16
    secretRefs:
      - name: gitlab-credentials
    serviceAccountName: gitlab
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
  stdioTransport: {}
  transportType: stdio
  timeout: 60s
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gitlab-credentials
  namespace: kmcp
spec:
  itemPath: vaults/Vicegerent/items/MCP - GitLab
