---
.custom:
  connect:
    image:
      repository: &connectRepository 1password/connect-api
      tag: &connectTag 1.8.2
  operator:
    image:
      repository: &operatorRepository 1password/onepassword-operator
      tag: &operatorTag 1.12.0
connect:
  credentialsName: op-credentials
  credentialsKey: 1password-credentials.json
  api:
    name: connect-api
    imageRepository: *connectRepository
    resources:
      requests:
        cpu: 12m
        memory: 125Mi
      limits:
        memory: 125Mi
  sync:
    imageRepository: 1password/connect-sync
    resources:
      requests:
        cpu: 12m
        memory: 125Mi
      limits:
        memory: 125Mi
  version: *connectTag
operator:
  create: true
  token:
    name: onepassword-token
    key: token
  autoRestart: false
  pollingInterval: 180
  imageRepository: *operatorRepository
  version: *operatorTag
  resources:
    requests:
      cpu: 10m
      memory: 110M
    limits:
      memory: 290M
